README.md
- I'll host these ebuilds.
- I'll keep instructions as detailed as I can.
=> fix gentoo installation

src/core/server.c, src/core/server_cmd.c, src/core/server_irc_event.c, src/core/server_irc_event.h, src/core/server_state.c, src/core/server_ui_event.c, src/core/server_ui_event.h, src/core/server_url.c, src/inc/server.h, src/inc/sirc/sirc_event.h, src/inc/sui/sui_event.h, src/sirc/sirc.c, src/sirc/sirc_cmd.c, src/sui/srain_server_buffer.c, src/sui/sui_event_hdr.c
=> Connection status control

po/srain.pot, po/zh_CN.po, src/core/server_irc_event.c
=> s/You has joined/You have joined/

contrib/pack/gentoo/README.md, contrib/pack/gentoo/latest/metadata.xml, contrib/pack/gentoo/latest/srain-9999.ebuild, contrib/pack/gentoo/stable/metadata.xml, contrib/pack/gentoo/stable/srain-0.06.3.ebuild
Close https://github.com/rtlanceroad/gentoo-srain/issues/1 .
=> Merge gentoo-srain repo to srain contrib

contrib/pack/flatpak/latest/im.srain.Srain.json, data/Srain.appdata.xml
This file contains metadata that software centers (gnome software, kde
discover, etc) use to display information such as screenshots, release
notes and similar.
=> Added appdata file

data/Srain.appdata.xml
Added release notes for the new version.
=> Update appdata file for 0.06.4

data/ui/buffer_menu.glade, src/core/app_ui_event.c, src/core/server.c, src/core/server_state.c, src/inc/core/server.h, src/inc/sui/sui_event.h, src/sui/sui_event_hdr.c, src/sui/sui_server_buffer.c
Added handler, event, and the pop-up menu element
Signed-off-by: Jianqiu Zhang <zhangjianqiu13@gmail.com>
=> Sui(impl): add reconnect in the server buffer pop-up menu

data/ui/join_panel.glade, src/sui/sui_join_panel.c
=> Make channel list in join panel sortable

src/core/app_irc_event.c, src/core/chat_command.c, src/inc/sirc/sirc_cmd.h, src/sirc/sirc_cmd.c
=> Add support for AWAY command

src/core/chat_command.c
=> Reverse arguments of invite command

data/themes/default-min.css, data/ui/message_list.glade, src/sui/sui_message_list.c
Reslove #158.
@VOID001 please review these change if you have time, I will merge it after you approved it.
=> Add scroll to bottom button for message list

src/core/app_irc_event.c
=> Fix endless SASL auth

.travis/dep.sh, data/builtin.cfg, data/ui/connect_panel.glade, data/ui/join_panel.glade, doc/changelog.rst, doc/faq.rst, doc/install.rst, src/Makefile, src/config/manager.c, src/config/password.c, src/config/password.h, src/config/reader.c, src/core/app_irc_event.c, src/core/app_ui_event.c, src/core/app_url.c, src/core/chat_command.c, src/core/chat_config.c, src/core/login_config.c, src/core/server_config.c, src/inc/config/config.h, src/inc/config/password.h, src/inc/core/server.h, src/inc/sui/sui.h, src/inc/sui/sui_config.h, src/sui/sui_app.c, src/sui/sui_app.h, src/sui/sui_config.c, src/sui/sui_connect_panel.c, src/sui/sui_join_panel.c
=> Password storage support

src/lib/pattern_set.c, src/lib/utils.c, src/sirc/sirc.c, src/sirc/sirc_utils.c, src/sui/sui_common.c, src/sui/sui_side_bar_item.c, src/sui/sui_url_previewer.c
=> Free all unfreed GError

src/sui/sui_url_previewer.c
=> Let pixbuf loader knows mime type

po/ru.po, po/srain.pot, po/zh_CN.po, src/config/password.c, src/config/reader.c
=> Works without libsecret

data/srain.appdata.xml
Provide valid appdata file to prevent complain of falthub package builder.
=> Valid appdata file

po/LANGS, po/nl.po
=> Added Dutch translation

src/core/app_irc_event.c
=> Add channel related errros to corresponding buffer

data/themes/bubble.css, data/themes/default-bubble-dark.css, data/themes/default-bubble.css, data/themes/default-min.css, data/ui/message_list.glade, data/ui/misc_message.glade, data/ui/recv_message.glade, data/ui/send_message.glade, src/render/mention_renderer.c, src/sui/sui_common.c, src/sui/sui_common.h, src/sui/sui_message.c, src/sui/sui_message.h, src/sui/sui_message_list.c, src/sui/sui_side_bar.c
* Add tow buttons for jumping to previous/next mentioned message
* Highlight the user nick appears in message
* Support to select multiple messages
* Improve the way of scroll to bottom
---
Preview:
=> Add buttons for jumping to mention message

src/sirc/sirc.c
=> Escape host before passing it to GSocketClient

src/core/server_state.c, src/sui/sui_chat_buffer.c
=> Fix some use-after-free cases

LICENSE
=> Add special exception with OpenSSL to LICENSE

script/gen-build-id.sh, src/core/app.c, src/core/app_irc_event.c, src/meson.build, src/sui/sui_app.c
This PR fixes job build-mingw.
=> Allow invalid version string

.github/workflows/build.yml
=> change setup-msys2@v1 to setup-msys2@v2

.github/workflows/pack-mingw64.sh, .github/workflows/release.yml
=> Use hardcode meson prefix in window build

src/sui/sui_url_previewer.c
=> Prevent crash when URL preview async task failed

src/sui/sui_user.c, src/sui/sui_user_list.c
=> Fix fix gdk warning

src/core/app_irc_event.c, src/sirc/sirc_event_hdr.c
https://modern.ircdocs.horse/#rplumodeis-221
=> Add support for RPL_UMODEIS

src/core/app_irc_event.c
=> Rejoin channel after nickserv auth

doc/commands.rst, src/core/chat_command.c, src/core/chat_command.h, src/inc/sui/sui.h, src/sui/sui.c, src/sui/sui_message_list.c, src/sui/sui_message_list.h
=> Add command `/clear` for clearing messages of current buffer

po/LINGUAS, po/fr.po, po/nl.po, po/ru.po, po/srain.pot, po/uk.po, src/core/chat_command.c, src/sui/sui_app.c
Also fix a typo in one of the original messages.
I preserved the English mnemonic characters; though it seems they are not used at all because they don't work on my computer. (Could it be because I use Wayland?)
=> Add French translation

.github/workflows/release.yml
=> Fix hardcoded meson prefix in release.yml

data/builtin.cfg, src/config/reader.c, src/inc/sui/sui_config.h, src/sui/sui_window.c
=> Add conf item for setting default server visiblity

src/sui/sui_theme.c
=> Detect nordic dark theme

src/core/app_ui_event.c, src/core/chat_command.c
=> Activate buffer if chat already exists

src/core/app_irc_event.c
=> End SASL negotiation at SASLSUCCESS

.github/workflows/build.yml, data/ui/app.glade, docs/install.rst, meson_options.txt, src/meson.build, src/sui/sui_app.c
Thanks to @ShadowRZ.
See also #260  
Close #398
=> Use libappindicator

data/builtin.cfg, src/config/reader.c, src/inc/sui/sui_config.h, src/sui/sui_app.c, src/sui/sui_message_list.c
fixes #382 
if you don't like this, then can it at least be optional? I think this functionality is vital to an irc client.
=> Scroll down when new message even if window is inactive

data/ui/app.glade, src/sui/sui_app.c
- AyatanaAppIndicator3 doc: https://lazka.github.io/pgi-docs/AyatanaAppIndicator3-0.1/index.html
- Attention icon does not work on waybar, why?
=> Some trayicon/appindicator fixes

docs/install.rst
The posted instructions for macos were not quite sufficient. I added the fixes I had to make.
=> Fix and update macos instructions

po/LINGUAS, po/zh_TW.po, src/sui/sui_app.c
=> Update zh_TW Traditional Chinese locale

docs/misc.rst, src/sui/sui_window.c
=> Sui(impl): Add <C-q> shortcut for quitting Srain (#223)

.github/workflows/pack-debian.sh, .github/workflows/release.yml
=> Fix release assets

data/metainfo/srain.metainfo.xml.in.in, docs/changelog.rst, docs/conf.py, meson.build
For https://aur.archlinux.org/packages/srain#comment-1027522
=> Release 1.8.1
