SrainApp/srain

- src/filter.c
- src/inc/filter.h
- src/srv/srv_event.c
- src/srv/srv_session_cmd.c
Add comman: /filter and /unfilter
Usage:
/filter filter_name #channel_name regex
/unfilter filter_name
example:
/filter test_a #lasttest .\*test.\*
/unfilter test_a
It's also allowed to create a filter can affect all channels, just change #channel_name to \*
TODO: Add enable/disable filter command and make it affect to chat log.
> add feature: filter

- CHANGELOG.rst
- doc/commands.rst
- src/command.c
- src/command_test.c
- src/inc/command.h
- src/inc/log.h
- src/inc/rc.h
- src/inc/ret.h
- src/inc/server.h
- src/inc/server_cmd.h
- src/inc/sirc/sirc_prefs.h
- src/inc/sui/sui_prefs.h
- src/inc/utils.h
- src/rc.c
- src/ret.c
- src/server/server.c
- src/server/server_cmd.c
- src/server/server_irc_event.c
- src/server/server_prefs.c
- src/server/server_ui_event.c
- src/server/user.c
- src/sirc_real/sirc_prefs.c
- src/srain.c
- src/sui_gtk/sui.c
- src/sui_gtk/sui_prefs.c
- src/utils.c
- The srain return value `SrnRet` allows function return a `int` with a message, and both caller and callee don't need to  manage the memory of these messages by themself.
- `/server` command, allow user create a server, specifies various parameters, connect to it and disconnect from it, `/server` also works well with prefs system :-), for the usage of `/server`, refer to `doc/commands.rst`(document not fininised yet)
- TODO: Document of `/server`, let prefs system use `SrnRet`
> SrnRet and /server command

- data/Srain.desktop
This value refers to the desktop file spec not the application version. It generally isn't needed.
https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys
> Remove bogus entry from desktop file

- im.srain.Srain.json
This allows for building Srain as a distro agnostic flatpak.
At this point it builds and runs fine on my machine, but it needs more testing.
Afterwards it may be a good idea to submit it to flathub so that people can easily find, install and update the builds.
> Add manifest for flatpak-builder

- contrib/pack/flatpak/latest/im.srain.Srain.json
The icon was not appearing in the 'about' dialog as intended because it
was getting renamed rather than copied.
There actually was a copy-icon option after all :)
> Fix icon not appearing in flatpak builds

- data/Srain.appdata.xml
This is an attempt to workaround issue https://github.com/flathub/im.srain.Srain/issues/1#, which tingping 
believes may be behind the appdata export problems in flathub.
> Add full appid to appdata file

- src/sui/sui_window.c
After 4dda195 the icon would no longer match the one defined in the glade files.
> Prevent send message icon from breaking on sending a message

- src/sirc/sirc_event_hdr.c
This brings more flexibility since some servers might send commands that are not all capital letters (e.g. `Cap` instead of `CAP`)
> Compare commands case-insensitively

- data/ui/window.glade
- src/sui/sui_side_bar.c
- src/sui/sui_window.c
> Use default button relief and use symbolic icons

- src/Makefile
Sets CC to gcc, if not otherwise specified.
https://www.gnu.org/software/make/manual/html_node/Origin-Function.html
This makes cross-compiling possible, as is seen working here: https://github.com/void-linux/void-packages/pull/19928
> Script(update): allow setting CC variable via environment

- src/inc/srain.h
- src/inc/utils.h
- src/lib/i18n.c
- src/lib/utils.c
- src/sirc/sirc.c
- src/sirc/sirc_cmd.c
- src/sirc/sirc_cmd_builder.c
- src/sirc/sirc_cmd_builder.h
- src/sirc/sirc_config.c
- src/sirc/sirc_parse.c
- src/sirc/sirc_parse.h
- Introduce SircCommandBuilder to build IRC message with legal length
- Deal with invalid UTF-8 sequence
- Prevent uncessary transcoding
> Truncate long message and Improve message transcoding

- data/builtin.cfg
Hey there,
I'm including:
* DALnet
* EFnet
* IRCnet
* Undernet
* Quakenet
Cheers,
Gus
> Adding more pre-defined servers, as per file TODO

- src/lib/libecdsaauth/base64.c
- src/sirc/sirc_cmd_builder.c
- src/sui/sui_chat_buffer.c
To fix build errors on some systems.
> Add includes to avoid implicit declarations errors

- .github/workflows/release-assets-upload.py
- .github/workflows/release-debian-package.sh
- .github/workflows/release.yml
- Github workflows file.
- Debian package script.
- Assets upload script.
> Add Github actions of the release event.

- src/render/mirc_colorize_renderer.c
debian annoy me with warning, so here is my "big fix" :)
```
I: srain: spelling-error-in-binary usr/bin/srain Closeing Closing
N: 
N:    Lintian found a spelling error in the given binary. Lintian has a list
N:    of common misspellings that it looks for. It does not have a dictionary
N:    like a spelling checker does.
N:    
N:    If the string containing the spelling error is translated with the help
N:    of gettext or a similar tool, please fix the error in the translations
N:    as well as the English text to avoid making the translations fuzzy. With
N:    gettext, for example, this means you should also fix the spelling
N:    mistake in the corresponding msgids in the *.po files.
N:    
N:    You can often find the word in the source code by running:
N:    
N:     grep -rw <word> …
```
> fix typo in DBG code

- src/lib/path.c
I'm seeing this on openSUSE Leap 15.1
```
lib/path.c: In function 'srn_get_executable_path':
lib/path.c:370:4: warning: implicit declaration of function 'realpath'; did you mean 'renameat'? [-Wimplicit-function-declaration]
realpath(PROC_SELF_EXE, rawPathName);
^~~~~~~~
renameat
```
> Fix implicit-declaration error on some systems

- src/lib/path.c
This PR provides the implementations of `srn_get_executable_path()` and `srn_get_executable_dir()` functions. This implementation should also work on other BSD OSs too, but I didn't get to test it.
You can read more about it in FreeBSD's [sysctl(3)](https://www.freebsd.org/cgi/man.cgi?query=sysctl&sektion=3&manpath=FreeBSD+12.1-RELEASE&arch=default&format=html) manpage.
Thanks!
> Add FreeBSD implementations for srn_get_executable_{path,dir}

- src/meson.build
Fixes parallel build fail with `ninja -j4` and more.
Multiple compilation jobs can try to compile files which include meta.h
before this file is created by another job. To avoid that, declare
explicit dependency on generated file.
More: https://mesonbuild.com/Wrap-best-practices-and-tips.html#declare-generated-headers-explicitly
> Script(fix): depend on generated header explicitly

- src/core/app_irc_event.c
- src/core/chat_command.c
- src/core/chat_command.h
This adds a /quote command for sending cusom IRC commands
Additionally processing of unknown numeric responses is cleaned up to properly show the response in the debug console, and extended to echo the response message in the server chat making the responses useful to the user even if not fully supported by srain.
> Add /quote command

- src/sui/sui_buffer.c
- src/sui/sui_chat_buffer.c
- src/sui/sui_completion.c
- src/sui/sui_user_list.c
> Make nick completion case-insensitive

- src/core/app_irc_event.c
ISUPPORT syntax: https://modern.ircdocs.horse/#rplisupport-005
Relevant bits from the [UTF8ONLY specification](https://ircv3.net/specs/extensions/utf8-only):
> Servers publishing this token MUST NOT relay content [...] containing non-UTF-8 data to clients
> If a client implementing this specification sees this token, they MUST set their outgoing encoding to UTF-8 without requiring any user intervention.
This has the following effects:
* With the default configuration, this does nothing because Srain uses UTF-8 by default
* If a non-UTF-8 encoding is specified, it overrides the user's configuration if the server advertises UTF8ONLY.
This seems to affect only the incoming encoding, because Srain always send UTF-8 regardless of how I configured it. (Which is nice IMO, but it looks like a …
> Implement ISUPPORT parsing + the UTF8ONLY IRCv3 specification

- src/core/app_irc_event.c
On channels with mode -n, people don't need to be in the channel
to send messages to it.
MODE and KICK can also be used by network bots or servers,
even if they are not joined.
> Add support for channel messages with origin out of channel

- src/core/app_irc_event.c
- src/core/server_cap.c
- src/inc/core/server.h
- src/inc/sirc/sirc_event.h
- src/sirc/sirc_event_hdr.c
- src/sirc/sirc_parse.c
- src/sirc/sirc_parse.h
Not doing anything with it yet, though.
If that's fine with you, I have another PR ready, to use [server-time](https://ircv3.net/specs/extensions/server-time)
> Add support for message-tags

- src/lib/command.c
I get this error in the console when using '/part' with no argument:
```
** (srain:1402455): CRITICAL **: 15:14:11.703: get_quote_arg: assertion 'ptr && arg && next' failed
```
because `ptr` is NULL.
This extra check avoids it.
> Silence assertion failure on '/part'

- src/core/app_irc_event.c
This happens on "CAP ACK" from Ergo and UnrealIRCd.
> Silence "Unknown capability" warning on trailing ' '

- src/core/message.c
- src/inc/sirc/sirc_context.h
- src/sirc/sirc_context.c
> Core(fix): sirc_message_context_get_time use-after-free

- src/core/app_irc_event.c
- src/inc/sirc/sirc_event.h
- src/sirc/sirc_event_hdr.c
Srain doesn't currently use any of the specs that depend on standard-replies,
but Ergo sometimes emits them in addition to/instead of numerics (typically
when trying to express an error that doesn't have a numeric).
This is mostly just to suppress the error
`_sirc_event_hdr: assertion 'events->unknown' failed` when failing SASL
authentication on Ergo.
https://ircv3.net/specs/extensions/standard-replies
Example when failing SASL auth:
> Add support for IRCv3 standard-replies

- doc/support.rst
- src/core/app_irc_event.c
- src/core/server_cap.c
- src/inc/core/server.h
https://ircv3.net/specs/extensions/invite-notify
Also remove the comments about IRCv3.1 / IRCv3.2, because IRCv3 does not
classify its specs this way anymore.
How to test:
1. connect to a network that supports invite-notify (eg. irc.ergo.chat)
2. join a room, get opped
3. ask another op to invite someone
4. "X invites Y into Z" appears on the chat
Behavior is unchanged when being invited (ie. it still creates a private chat with the inviter)
> Add support for invite-notify

- src/core/app_irc_event.c
- src/core/server.c
- src/inc/core/server.h
> Suppress error message after connection fails once

- src/config/reader.c
- src/filter/log_filter.c
- src/inc/core/chat.h
> Skip log filter when log in chat config disabled

- data/builtin.cfg
https://discourse.gnome.org/t/gnome-moves-away-from-gimpnet-on-nov-25-15-00-utc/12046/17
Close #407.
> Data(cleanup): remove GIMPNet

- data/builtin.cfg
- src/config/reader.c
- src/core/app_config.c
- src/inc/sui/sui_config.h
- src/sui/sui_config.c
- src/sui/sui_side_bar.c
- src/sui/sui_side_bar_item.c
- src/sui/sui_side_bar_item.h
Adds a way to sort channels alphabetically in the sidebar
Notes for the review:
* I am not quite sure about the naming
* There are no checks done on the new `sidebar-sort` configuration value, but no other settings appear to have such checks. The *default* value I have provided in `builtin.cfg` is de facto arbitrary.
* I wonder if there is a better way to access the configuration from `list_sort_func`
* It's possible that I have missed some error checks to be done
> Sui(impl): Add chat list order configuration

- src/sirc/sirc_event_hdr.c
Closes #379 
I'm not sure if `g_time_zone_new_local()` could be called more globally instead of on each message.
I also wonder if the timezone support handles daylight saving (if you'd keep Srain open when the timezone offset changes, would it keep outputting the right date if the `GTimeZone` object doesn't change?), though it would be a minor issue if it doesn't.
> Sirc(fix): Convert IRCv3 received server-time to local timezone (#379)

- src/core/app.c
- src/filter/filter2.h
- src/inc/srain.h
In C23 (the default for GCC 15), bool is a keyword, so typedef needs to be removed.
```
../srain-1.8.0/src/inc/srain.h:26:18: error: two or more data types in declaration specifiers
26 | typedef gboolean bool;
|                  ^~~~
```
```
../srain-1.8.0/src/filter/user_filter.c:32:15: error: initialization of ‘SrnRet (*)(const SrnMessage *)’ {aka ‘int (*)(const struct _SrnMessage *)’} from incompatible pointe
r type ‘_Bool (*)(const SrnMessage *)’ {aka ‘_Bool (*)(const struct _SrnMessage *)’} [-Wincompatible-pointer-types]
32 |     .filter = filter,
|               ^~~~~~
```
Also fixes an oversight in 7f27c41.
```
../srain-1.8.0/src/core/app.c: In function ‘srn_application_add_server’:
../srain-1.8.0/src/core/app.c:237:15: error: too many arguments to function ‘srn_server_config_new’ …
```
> Core(fix): remove bool typedef in C23
